export type AccountingAccountGroupKey =
  | "ASSET"
  | "LIABILITY"
  | "EQUITY"
  | "INCOME"
  | "EXPENSE";

export type AccountingAccountNature = "DEBIT" | "CREDIT";

export type AccountingAccountCatalogItem = {
  code: string;
  name: string;
  groupKey: AccountingAccountGroupKey;
  groupLabel: string;
  parentCode: string | null;
  level: number;
  acceptsPostings: boolean;
  defaultNature: AccountingAccountNature;
  description: string;
  system: boolean;
};

export const ACCOUNT_CODES = {
  accountsReceivable: "110101",
  cashDrawer: "110201",
  bankClearing: "110301",
  inventoryMerchandise: "110401",
  vatCredit: "110501",
  accountsPayable: "210101",
  vatPayable: "210201",
  cashManualBridge: "230101",
  revenue: "410101",
  refundExpense: "510101",
  professionalServicesExpense: "510205",
} as const;

export const ACCOUNTING_CHART: AccountingAccountCatalogItem[] = [
  {
    code: "1",
    name: "Activo",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: null,
    level: 1,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Raiz de los bienes y derechos controlados por el negocio.",
    system: true,
  },
  {
    code: "11",
    name: "Activo corriente",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1",
    level: 2,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Activos de realizacion o consumo dentro del ciclo operativo.",
    system: true,
  },
  {
    code: "1101",
    name: "Cuentas por cobrar comerciales",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "11",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Derechos de cobro originados por ventas y operaciones relacionadas.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.accountsReceivable,
    name: "Cuentas por cobrar clientes",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Cuenta usada para registrar la venta devengada y su posterior cancelacion.",
    system: true,
  },
  {
    code: "110102",
    name: "Anticipos entregados a proveedores",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Desembolsos anticipados pendientes de liquidacion con proveedores.",
    system: true,
  },
  {
    code: "110103",
    name: "Otras cuentas por cobrar",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Derechos de cobro varios no clasificados como clientes.",
    system: true,
  },
  {
    code: "1102",
    name: "Caja y equivalentes",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "11",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Disponibilidades inmediatas en efectivo o fondos de uso directo.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.cashDrawer,
    name: "Caja general",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Cuenta usada para cobros en efectivo, devoluciones y movimientos manuales de caja.",
    system: true,
  },
  {
    code: "110202",
    name: "Caja chica",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Fondo fijo destinado a gastos menores de operacion.",
    system: true,
  },
  {
    code: "110203",
    name: "Bancos nacionales",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Disponibilidades depositadas en cuentas bancarias de uso corriente.",
    system: true,
  },
  {
    code: "1103",
    name: "Bancos y compensacion",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "11",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Saldos transitorios o bancarios asociados a cobros electronicos.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.bankClearing,
    name: "Bancos / cuenta puente",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1103",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Cuenta puente para cobros por tarjeta, transferencia u otros medios financieros.",
    system: true,
  },
  {
    code: "110302",
    name: "Tarjetas por acreditar",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1103",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Valores pendientes de acreditacion por procesadores de tarjetas.",
    system: true,
  },
  {
    code: "110303",
    name: "Transferencias por confirmar",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1103",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Transferencias bancarias recibidas aun no conciliadas.",
    system: true,
  },
  {
    code: "1104",
    name: "Inventarios",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "11",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Existencias disponibles para venta o consumo productivo.",
    system: true,
  },
  {
    code: "110401",
    name: "Inventario de mercaderias",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1104",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Mercaderia adquirida para su posterior comercializacion.",
    system: true,
  },
  {
    code: "110402",
    name: "Inventario de insumos y materiales",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1104",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Materiales y suministros pendientes de consumo.",
    system: true,
  },
  {
    code: "110403",
    name: "Mercaderia en transito",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1104",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Compras enviadas por el proveedor y aun no recibidas formalmente.",
    system: true,
  },
  {
    code: "1105",
    name: "Impuestos y creditos tributarios",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "11",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Saldos a favor y derechos de recuperacion tributaria.",
    system: true,
  },
  {
    code: "110501",
    name: "IVA credito tributario",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1105",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "IVA pagado en compras que puede compensarse contra debitos fiscales.",
    system: true,
  },
  {
    code: "110502",
    name: "Retenciones por cobrar",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1105",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Retenciones efectuadas por terceros pendientes de aplicacion.",
    system: true,
  },
  {
    code: "12",
    name: "Activo no corriente",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1",
    level: 2,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Activos destinados al uso permanente o recuperacion de largo plazo.",
    system: true,
  },
  {
    code: "1201",
    name: "Propiedad planta y equipo",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "12",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Bienes tangibles empleados en la operacion del negocio.",
    system: true,
  },
  {
    code: "120101",
    name: "Muebles y enseres",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1201",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Mobilario y equipamiento menor de uso administrativo o comercial.",
    system: true,
  },
  {
    code: "120102",
    name: "Equipos de computacion",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1201",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Computadores, impresoras y dispositivos utilizados por la operacion.",
    system: true,
  },
  {
    code: "120103",
    name: "Maquinaria y equipo",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1201",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Activos de uso productivo o tecnico dentro del negocio.",
    system: true,
  },
  {
    code: "1202",
    name: "Depreciacion acumulada",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "12",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Cuentas correctoras del valor de propiedad planta y equipo.",
    system: true,
  },
  {
    code: "120201",
    name: "Depreciacion acumulada muebles y enseres",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1202",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Depreciacion acumulada asociada a muebles y enseres.",
    system: true,
  },
  {
    code: "120202",
    name: "Depreciacion acumulada equipos de computacion",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1202",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Depreciacion acumulada asociada a equipos de computacion.",
    system: true,
  },
  {
    code: "120203",
    name: "Depreciacion acumulada maquinaria y equipo",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1202",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Depreciacion acumulada asociada a maquinaria y equipo.",
    system: true,
  },
  {
    code: "13",
    name: "Otros activos",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1",
    level: 2,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Activos diferidos, depositos y otros rubros no corrientes o especiales.",
    system: true,
  },
  {
    code: "1301",
    name: "Gastos pagados por anticipado",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "13",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Pagos efectuados por servicios cuyo beneficio se consume en periodos futuros.",
    system: true,
  },
  {
    code: "130101",
    name: "Arriendos pagados por anticipado",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1301",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Canon de arriendo cancelado antes de su devengo.",
    system: true,
  },
  {
    code: "130102",
    name: "Seguros pagados por anticipado",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1301",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Primas de seguro pagadas para cobertura de periodos futuros.",
    system: true,
  },
  {
    code: "1302",
    name: "Depositos y garantias",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "13",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Valores entregados como respaldo contractual o legal.",
    system: true,
  },
  {
    code: "130201",
    name: "Garantias entregadas",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1302",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Garantias monetarias entregadas a terceros.",
    system: true,
  },
  {
    code: "2",
    name: "Pasivo",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: null,
    level: 1,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Raiz de obligaciones y compromisos asumidos por el negocio.",
    system: true,
  },
  {
    code: "21",
    name: "Pasivo corriente",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Obligaciones exigibles dentro del siguiente ciclo operativo.",
    system: true,
  },
  {
    code: "2101",
    name: "Proveedores y cuentas por pagar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "21",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Obligaciones comerciales con proveedores y terceros.",
    system: true,
  },
  {
    code: "210101",
    name: "Proveedores locales",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Facturas y cuentas pendientes con proveedores nacionales.",
    system: true,
  },
  {
    code: "210102",
    name: "Cuentas por pagar varias",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Obligaciones con terceros no clasificadas como proveedores.",
    system: true,
  },
  {
    code: "2102",
    name: "Pasivos tributarios",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "21",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Obligaciones tributarias generadas por la operacion.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.vatPayable,
    name: "IVA por pagar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Cuenta de IVA generado por ventas gravadas.",
    system: true,
  },
  {
    code: "210202",
    name: "Retenciones por pagar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Retenciones efectuadas a terceros pendientes de declaracion o pago.",
    system: true,
  },
  {
    code: "210203",
    name: "Impuesto a la renta por pagar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Obligacion estimada por impuesto a la renta del periodo.",
    system: true,
  },
  {
    code: "2103",
    name: "Obligaciones laborales",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "21",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Compromisos derivados de la relacion laboral y beneficios del personal.",
    system: true,
  },
  {
    code: "210301",
    name: "Sueldos por pagar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2103",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Remuneraciones acumuladas pendientes de pago al personal.",
    system: true,
  },
  {
    code: "210302",
    name: "Beneficios sociales por pagar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2103",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Obligaciones por decimos, vacaciones u otros beneficios laborales.",
    system: true,
  },
  {
    code: "2104",
    name: "Pasivos financieros de corto plazo",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "21",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Obligaciones financieras con vencimiento dentro del corto plazo.",
    system: true,
  },
  {
    code: "210401",
    name: "Prestamos bancarios corto plazo",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2104",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Financiamientos bancarios exigibles en el corto plazo.",
    system: true,
  },
  {
    code: "210402",
    name: "Tarjetas de credito por pagar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2104",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Obligaciones pendientes derivadas del uso de tarjetas de credito.",
    system: true,
  },
  {
    code: "22",
    name: "Pasivo no corriente",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Obligaciones con vencimiento superior a un ejercicio.",
    system: true,
  },
  {
    code: "2201",
    name: "Obligaciones financieras de largo plazo",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "22",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Prestamos y financiamientos de largo plazo.",
    system: true,
  },
  {
    code: "220101",
    name: "Prestamos bancarios largo plazo",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2201",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Financiamientos bancarios con vencimiento superior a un ejercicio.",
    system: true,
  },
  {
    code: "220102",
    name: "Arrendamientos financieros por pagar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2201",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Obligaciones pendientes por contratos de arrendamiento financiero.",
    system: true,
  },
  {
    code: "23",
    name: "Pasivos transitorios",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Puentes operativos para movimientos que luego se regularizan.",
    system: true,
  },
  {
    code: "2301",
    name: "Puentes operativos",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "23",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Contrapartidas temporales usadas por movimientos manuales y conciliaciones.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.cashManualBridge,
    name: "Puente movimientos manuales de caja",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2301",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Cuenta puente para aportes y retiros manuales de caja.",
    system: true,
  },
  {
    code: "230102",
    name: "Ingresos diferidos por aplicar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2301",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Cobros recibidos pendientes de reconocimiento contable definitivo.",
    system: true,
  },
  {
    code: "230103",
    name: "Cobros por identificar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2301",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Fondos recibidos aun no asociados a un cliente u operacion concreta.",
    system: true,
  },
  {
    code: "24",
    name: "Otras cuentas por pagar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Obligaciones de distinta naturaleza no clasificadas en otros rubros.",
    system: true,
  },
  {
    code: "2401",
    name: "Otras obligaciones",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "24",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Pasivos diversos con terceros o socios.",
    system: true,
  },
  {
    code: "240101",
    name: "Anticipos de clientes",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2401",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Valores recibidos por adelantado de clientes pendientes de facturacion o entrega.",
    system: true,
  },
  {
    code: "240102",
    name: "Dividendos por pagar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2401",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Distribuciones aprobadas y pendientes de pago a socios o accionistas.",
    system: true,
  },
  {
    code: "240103",
    name: "Otras cuentas por pagar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2401",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Obligaciones varias con terceros no asignadas a un rubro especifico.",
    system: true,
  },
  {
    code: "3",
    name: "Patrimonio",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: null,
    level: 1,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Participacion residual de los propietarios sobre los activos netos.",
    system: true,
  },
  {
    code: "31",
    name: "Capital",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "3",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Aportes permanentes de socios o accionistas al negocio.",
    system: true,
  },
  {
    code: "3101",
    name: "Capital social",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "31",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Capital comprometido y aportado por los propietarios.",
    system: true,
  },
  {
    code: "310101",
    name: "Aportes de socios",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "3101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Aportes realizados por socios o accionistas al patrimonio.",
    system: true,
  },
  {
    code: "310102",
    name: "Aportes para futuras capitalizaciones",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "3101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Aportes entregados por socios pendientes de formalizacion como capital.",
    system: true,
  },
  {
    code: "32",
    name: "Reservas",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "3",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Apropiaciones patrimoniales constituidas segun politica o normativa.",
    system: true,
  },
  {
    code: "3201",
    name: "Reserva legal",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "32",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Reserva constituida por mandato legal.",
    system: true,
  },
  {
    code: "320101",
    name: "Reserva legal constituida",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "3201",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Saldo acumulado de la reserva legal.",
    system: true,
  },
  {
    code: "3202",
    name: "Otras reservas",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "32",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Reservas estatutarias o voluntarias establecidas por la administracion.",
    system: true,
  },
  {
    code: "320201",
    name: "Reserva facultativa",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "3202",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Reserva creada por decision de socios o administracion.",
    system: true,
  },
  {
    code: "33",
    name: "Resultados acumulados",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "3",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Utilidades o perdidas retenidas de ejercicios anteriores.",
    system: true,
  },
  {
    code: "3301",
    name: "Resultados de ejercicios anteriores",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "33",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Acumulacion historica de resultados ya cerrados.",
    system: true,
  },
  {
    code: "330101",
    name: "Utilidades retenidas",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "3301",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Resultados positivos no distribuidos de ejercicios anteriores.",
    system: true,
  },
  {
    code: "330102",
    name: "Perdidas acumuladas",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "3301",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Resultados negativos pendientes de compensacion de ejercicios anteriores.",
    system: true,
  },
  {
    code: "34",
    name: "Resultado del ejercicio",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "3",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Resultado generado por la operacion del periodo actual.",
    system: true,
  },
  {
    code: "3401",
    name: "Utilidad o perdida del ejercicio",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "34",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Cuenta de cierre para concentrar el resultado del periodo.",
    system: true,
  },
  {
    code: "340101",
    name: "Resultado del ejercicio",
    groupKey: "EQUITY",
    groupLabel: "Patrimonio",
    parentCode: "3401",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Saldo final de utilidades o perdidas del ejercicio en curso.",
    system: true,
  },
  {
    code: "4",
    name: "Ingresos",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: null,
    level: 1,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Raiz de ingresos operacionales y no operacionales.",
    system: true,
  },
  {
    code: "41",
    name: "Ingresos operacionales",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "4",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Ingresos originados en la actividad principal del negocio.",
    system: true,
  },
  {
    code: "4101",
    name: "Ventas",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "41",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Agrupador de ingresos por venta de bienes.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.revenue,
    name: "Ingresos por ventas",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "4101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Cuenta de reconocimiento del ingreso neto de ventas.",
    system: true,
  },
  {
    code: "410102",
    name: "Devoluciones en ventas",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "4101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Contraingreso por devoluciones o anulaciones de ventas.",
    system: true,
  },
  {
    code: "410103",
    name: "Descuentos en ventas",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "4101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Contraingreso por descuentos y rebajas concedidos a clientes.",
    system: true,
  },
  {
    code: "4102",
    name: "Ingresos por servicios",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "41",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Facturacion derivada de servicios prestados.",
    system: true,
  },
  {
    code: "410201",
    name: "Ingresos por servicios",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "4102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Cuenta para reconocimiento de ingresos por servicios.",
    system: true,
  },
  {
    code: "42",
    name: "Otros ingresos",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "4",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Ingresos financieros y otros rubros no operacionales.",
    system: true,
  },
  {
    code: "4201",
    name: "Ingresos financieros",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "42",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Rendimientos obtenidos por inversiones o disponibilidades financieras.",
    system: true,
  },
  {
    code: "420101",
    name: "Intereses ganados",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "4201",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Intereses devengados a favor del negocio.",
    system: true,
  },
  {
    code: "420102",
    name: "Rendimientos bancarios",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "4201",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Rendimientos reconocidos por saldos o inversiones bancarias.",
    system: true,
  },
  {
    code: "4202",
    name: "Otros ingresos no operacionales",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "42",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Ingresos esporadicos o ajenos al giro principal.",
    system: true,
  },
  {
    code: "420201",
    name: "Otros ingresos diversos",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "4202",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Ingresos extraordinarios o complementarios no recurrentes.",
    system: true,
  },
  {
    code: "5",
    name: "Gastos",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: null,
    level: 1,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Raiz de gastos, costos y egresos del negocio.",
    system: true,
  },
  {
    code: "51",
    name: "Gastos operativos",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5",
    level: 2,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Gastos y ajustes que afectan la operacion corriente.",
    system: true,
  },
  {
    code: "5101",
    name: "Devoluciones y ajustes",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "51",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Agrupador de devoluciones registradas desde caja y ajustes similares.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.refundExpense,
    name: "Gasto por devoluciones",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Cuenta de contrapartida para devoluciones registradas desde caja.",
    system: true,
  },
  {
    code: "5102",
    name: "Gastos administrativos",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "51",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Egresos asociados a la administracion general del negocio.",
    system: true,
  },
  {
    code: "510201",
    name: "Sueldos administrativos",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Remuneraciones del personal administrativo.",
    system: true,
  },
  {
    code: "510202",
    name: "Arriendos administrativos",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Canon de arriendo de oficinas, locales u otras instalaciones administrativas.",
    system: true,
  },
  {
    code: "510203",
    name: "Servicios basicos",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Consumos de agua, luz, telecomunicaciones u otros servicios recurrentes.",
    system: true,
  },
  {
    code: "510204",
    name: "Utiles de oficina",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Materiales y suministros utilizados por la administracion.",
    system: true,
  },
  {
    code: "510205",
    name: "Honorarios profesionales",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Servicios profesionales recibidos de terceros.",
    system: true,
  },
  {
    code: "5103",
    name: "Gastos de ventas",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "51",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Egresos vinculados a la comercializacion y entrega de productos o servicios.",
    system: true,
  },
  {
    code: "510301",
    name: "Comisiones de ventas",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5103",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Comisiones reconocidas por gestion comercial o ventas realizadas.",
    system: true,
  },
  {
    code: "510302",
    name: "Publicidad y promocion",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5103",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Campanas, promociones y gastos de posicionamiento comercial.",
    system: true,
  },
  {
    code: "510303",
    name: "Fletes y entregas",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5103",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Costos de transporte y despacho relacionados con la venta.",
    system: true,
  },
  {
    code: "5104",
    name: "Gastos financieros",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "51",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Egresos originados por el uso de servicios o instrumentos financieros.",
    system: true,
  },
  {
    code: "510401",
    name: "Intereses y comisiones bancarias",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5104",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Cargos financieros reconocidos por bancos u otras entidades.",
    system: true,
  },
  {
    code: "5105",
    name: "Depreciaciones y amortizaciones",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "51",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Reconocimiento periodico del consumo de activos fijos o diferidos.",
    system: true,
  },
  {
    code: "510501",
    name: "Depreciacion del periodo",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5105",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Gasto por depreciacion del periodo sobre activos fijos.",
    system: true,
  },
  {
    code: "510502",
    name: "Amortizacion del periodo",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5105",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Gasto por amortizacion de activos diferidos o intangibles.",
    system: true,
  },
  {
    code: "5106",
    name: "Impuestos y contribuciones",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "51",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Tributos y cargas no recuperables asociados a la operacion.",
    system: true,
  },
  {
    code: "510601",
    name: "Impuestos municipales",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5106",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Tasas e impuestos municipales asumidos por el negocio.",
    system: true,
  },
  {
    code: "510602",
    name: "Contribuciones y tasas",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5106",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Contribuciones, licencias o tasas no clasificadas en otros rubros.",
    system: true,
  },
  {
    code: "5107",
    name: "Otros gastos",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "51",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Gastos diversos o no recurrentes de la operacion.",
    system: true,
  },
  {
    code: "510701",
    name: "Perdidas no operacionales",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5107",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Perdidas extraordinarias o eventos ajenos a la operacion normal.",
    system: true,
  },
  {
    code: "510702",
    name: "Mermas y ajustes de inventario",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5107",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Ajustes por deterioro, faltantes o mermas de inventario.",
    system: true,
  },
  {
    code: "52",
    name: "Costos",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5",
    level: 2,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Costos directos asociados a bienes vendidos o servicios prestados.",
    system: true,
  },
  {
    code: "5201",
    name: "Costo de ventas",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "52",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Costo directo de los bienes o insumos consumidos para la venta.",
    system: true,
  },
  {
    code: "520101",
    name: "Costo de mercaderias vendidas",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5201",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Costo reconocido por mercaderias efectivamente vendidas.",
    system: true,
  },
  {
    code: "520102",
    name: "Consumo de insumos",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5201",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Consumo de insumos y materiales aplicados a la prestacion o produccion.",
    system: true,
  },
];

const ACCOUNTING_ACCOUNT_MAP = new Map(
  ACCOUNTING_CHART.map((account) => [account.code, account]),
);

export function listAccountingAccounts() {
  return ACCOUNTING_CHART;
}

export function getAccountingAccountByCode(code: string) {
  return ACCOUNTING_ACCOUNT_MAP.get(code) ?? null;
}
