export type AccountingAccountGroupKey =
  | "ASSET"
  | "LIABILITY"
  | "INCOME"
  | "EXPENSE";

export type AccountingAccountNature = "DEBIT" | "CREDIT";

export type AccountingAccountCatalogItem = {
  code: string;
  name: string;
  groupKey: AccountingAccountGroupKey;
  groupLabel: string;
  parentCode: string | null;
  level: number;
  acceptsPostings: boolean;
  defaultNature: AccountingAccountNature;
  description: string;
  system: boolean;
};

export const ACCOUNT_CODES = {
  accountsReceivable: "110101",
  cashDrawer: "110201",
  bankClearing: "110301",
  vatPayable: "210201",
  cashManualBridge: "230101",
  revenue: "410101",
  refundExpense: "510101",
} as const;

export const ACCOUNTING_CHART: AccountingAccountCatalogItem[] = [
  {
    code: "1",
    name: "Activo",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: null,
    level: 1,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Raiz de cuentas activas del catalogo base.",
    system: true,
  },
  {
    code: "11",
    name: "Activo corriente",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1",
    level: 2,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Caja, bancos y cuentas por cobrar de corto plazo.",
    system: true,
  },
  {
    code: "1101",
    name: "Cuentas por cobrar comerciales",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "11",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Derechos de cobro derivados de ventas devengadas.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.accountsReceivable,
    name: "Cuentas por cobrar clientes",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Cuenta usada para registrar la venta devengada y su posterior cancelacion.",
    system: true,
  },
  {
    code: "1102",
    name: "Caja y equivalentes",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "11",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Efectivo operativo disponible en caja.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.cashDrawer,
    name: "Caja general",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Cuenta usada para cobros en efectivo, devoluciones y movimientos manuales de caja.",
    system: true,
  },
  {
    code: "1103",
    name: "Bancos y compensacion",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "11",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Saldos transitorios o bancarios asociados a cobros electronicos.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.bankClearing,
    name: "Bancos / cuenta puente",
    groupKey: "ASSET",
    groupLabel: "Activo",
    parentCode: "1103",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Cuenta puente para cobros por tarjeta, transferencia u otros medios financieros.",
    system: true,
  },
  {
    code: "2",
    name: "Pasivo",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: null,
    level: 1,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Raiz de obligaciones del catalogo base.",
    system: true,
  },
  {
    code: "21",
    name: "Pasivos tributarios",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Obligaciones tributarias generadas por la operacion.",
    system: true,
  },
  {
    code: "2102",
    name: "IVA generado",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "21",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Agrupador del impuesto trasladado en ventas.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.vatPayable,
    name: "IVA por pagar",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2102",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Cuenta de IVA generado por ventas gravadas.",
    system: true,
  },
  {
    code: "23",
    name: "Pasivos transitorios",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Puentes operativos para movimientos que luego se regularizan.",
    system: true,
  },
  {
    code: "2301",
    name: "Puentes operativos",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "23",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Contrapartidas temporales usadas por movimientos manuales.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.cashManualBridge,
    name: "Puente movimientos manuales de caja",
    groupKey: "LIABILITY",
    groupLabel: "Pasivo",
    parentCode: "2301",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Cuenta puente para aportes y retiros manuales de caja.",
    system: true,
  },
  {
    code: "4",
    name: "Ingresos",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: null,
    level: 1,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Raiz de ingresos operacionales.",
    system: true,
  },
  {
    code: "41",
    name: "Ingresos operacionales",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "4",
    level: 2,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Ventas y otros ingresos del giro principal.",
    system: true,
  },
  {
    code: "4101",
    name: "Ventas",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "41",
    level: 3,
    acceptsPostings: false,
    defaultNature: "CREDIT",
    description: "Agrupador de ingresos por ventas.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.revenue,
    name: "Ingresos por ventas",
    groupKey: "INCOME",
    groupLabel: "Ingresos",
    parentCode: "4101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "CREDIT",
    description: "Cuenta de reconocimiento del ingreso neto de ventas.",
    system: true,
  },
  {
    code: "5",
    name: "Gastos",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: null,
    level: 1,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Raiz de gastos operativos y ajustes.",
    system: true,
  },
  {
    code: "51",
    name: "Gastos operativos",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5",
    level: 2,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Gastos y ajustes que afectan el resultado operativo.",
    system: true,
  },
  {
    code: "5101",
    name: "Devoluciones y ajustes",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "51",
    level: 3,
    acceptsPostings: false,
    defaultNature: "DEBIT",
    description: "Agrupador de devoluciones registradas desde caja.",
    system: true,
  },
  {
    code: ACCOUNT_CODES.refundExpense,
    name: "Gasto por devoluciones",
    groupKey: "EXPENSE",
    groupLabel: "Gastos",
    parentCode: "5101",
    level: 4,
    acceptsPostings: true,
    defaultNature: "DEBIT",
    description: "Cuenta de contrapartida para devoluciones registradas desde caja.",
    system: true,
  },
];

const ACCOUNTING_ACCOUNT_MAP = new Map(
  ACCOUNTING_CHART.map((account) => [account.code, account]),
);

export function listAccountingAccounts() {
  return ACCOUNTING_CHART;
}

export function getAccountingAccountByCode(code: string) {
  return ACCOUNTING_ACCOUNT_MAP.get(code) ?? null;
}
